x = 0:0.1:3;
subplot(4,1,1)
plot(x, x.*sin(x), '-->m', x, x.^5/100, 'b', x, cos(x), '<r')
xlabel("x -> ")
ylabel("y -> ")
legend("x*sine", "weird function", "cosine")
title("Aplicatie smekeruta")
subplot(4,1,2)
fplot("[x*sin(x)]", [0, 3], '.->')
subplot(4,1,3)
fplot("[x^5/100]", [0, 3], '.->')
subplot(4,1,4)
fplot("[cos(x)]", [0, 3], '.->')